#!/bin/bash -vx

HJEM=$HOME/buildtool
IN=~/buildtool/apk_in
OUT=~/buildtool/apk_out
DEC=~/buildtool/apk_in/decompiled
SRC=~/buildtool/source_roms
FIX=~/buildtool/src_fix
FLASH=~/buildtool/flashable
LOG=~/buildtool/log
MODS=~/buildtool/mods
MAIN=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/main
DEVICE=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/device/m0
tlock=~/buildtool/flashable/template/system/media/theme/default
dst=~/buildtool/flashable/system/media/theme/default
src=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/extras/lockscreen

source $HJEM/functions.sh

clear

while [ answer != "0" ] 
do
clear
echo "|----------------------------------------------------------------|"
echo "|                                                                |"
echo "|                       MIUI building script                     |"
echo "|                                                 -By 1982Strand |"
echo "|----------------------------------------------------------------|"
echo "|                                                                |"
echo "|                                                                |"
echo "|                                                                |"
echo "|                                                                |"
echo "|----------------------------------------------------------------|"
echo "| 1.  Install frameworks        ||                               |"
echo "| 2.  Decompile all apks/jars   ||                               |"
echo "| 3.  Add translations          ||                               |"
echo "| 4.  Fix MIUI sources          || 13. Fix official sources      |"
echo "| 5.  Add predefined Mods       || 14. Patch & Build off. ROM    |"
echo "| 6.  Recompile apks/jars       ||                               |"
echo "| 7.  Inject resources          ||                               |"
echo "| 8.  Optimize pngs             ||                               |"
echo "| 9.  Zipalign apks             ||                               |"
echo "| 10. Build Flashable Zip       ||                               |"
echo "| 11. Decompile single apk      ||                               |"
echo "| 12. Recompile single apk      ||                               |"
echo "|                               || e. Extract apks from zip      |"
echo "|                               ||                               |"
echo "|  t. test                      || c. Cleaning Options           |"
echo "|----------------------------------------------------------------|"
echo "|x - Exit                                                        |"
echo "|----------------------------------------------------------------|"
printf %s " Select an Option: "
read -p " " answer
    case $answer in
       1) clear
       install_frameworks
       ;;
       2) clear
       decompile_apks
       ;;
       3) clear
       add_translations
       ;;
       4) clear
       source_fix
       ;;
       5) clear
       mods
       ;;
       6) clear
       recompile_apks
       ;;
       7) clear
       inject_res
       ;;
       8) clear
       opt_png
       ;;
       9) clear
       zipalign
       ;;
       10) clear
       flashable
       ;;
       11) clear
       decompile_single
       ;;
       12) clear
       recompile_single
       ;;
       13) clear
       source_fix_official
       ;;
       14) clear
       patch_miui
       ;;
       e) clear
       pull
       ;;
       c) clear
       clean_menu
       ;;
       t) clear
       lav_mappe
       ;;
       x) clear 
       exit;;
       *) echo ""
          echo "invalid menu choice"
       ;;
   esac
   echo ""
   echo "" 
   echo "[--- Press RETURN for menu ---]"
   read key
done

