#!/bin/bash
#
#  Tool is developed primarily to work with MIUI roms, from miuiandroid.com, for the Samsung Galaxy S3
#  
#  It is focusing on adding danish translations for a given rom, creating a language pack for it
#  
#  Credits to:
#
#  - Soupmagnet (xda): For great support, explaining regex and in writing the code
#  - Acid (miuiandroid): For inspiration and help with code (This script wouldn't be existing if i didn't know this guy!)
#  - iBotpeaches (miuiandroid): For Apktool, sort script and 3way mod code
#  - TommyTomatoe: For inspiration and png optimizer script
#  - Xiaomi/patchrom: For rmline.sh script (and of course the original rom)
#  - Some guys from stackoverflow.com: For support in writing the code
#
#
#

HJEM=$HOME/buildtool
IN=~/buildtool/apk_in
OUT=~/buildtool/apk_out
DEC=~/buildtool/apk_in/decompiled
SRC=~/buildtool/source_roms
FIX=~/buildtool/src_fix
SIGN=~/buildtool/signing
FLASH=~/buildtool/flashable
LOG=~/buildtool/log
MODS=~/buildtool/mods
MAIN=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/main
DEVICE=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/device/m0
XTRA=~/buildtool/translations/XML_MIUI-v5_Danish/Danish/extras

source $HJEM/functions.sh

clear

while [ answer != "0" ] 
do
clear
echo "|----------------------------------------------------------------|"
echo "|                                                                |"
echo "|                      MIUI V5 building script                   |"
echo "|                                                 -By 1982Strand |"
echo "|----------------------------------------------------------------|"
echo "|                                                                |"
echo "|                                                                |"
echo "|                                                                |"
echo "|                                                                |"
echo "|----------------------------------------------------------------|"
echo "| 1.  Install frameworks        ||                               |"
echo "| 2.  Decompile all apks/jars   ||                               |"
echo "| 3.  Add translations          ||                               |"
echo "| 4.  Fix MIUI sources          ||                               |"
echo "| 5.  Add predefined Mods       ||                               |"
echo "| 6.  Recompile apks/jars       ||                               |"
echo "| 7.  Inject resources          ||                               |"
echo "| 8.  Optimize pngs             ||                               |"
echo "| 9.  Zipalign apks             ||                               |"
echo "| 10. Signing Options           ||                               |"
echo "| 11. Build Flashable Zip       ||                               |"
echo "| 12. Decompile single apk      ||                               |"
echo "| 13. Recompile single apk      || e. Extract apks from zip      |"
echo "|                               ||                               |"
echo "|                               || c. Cleaning Options           |"
echo "|----------------------------------------------------------------|"
echo "|x - Exit                                                        |"
echo "|----------------------------------------------------------------|"
printf %s " Select an Option: "
read -p " " answer
    case $answer in
       1) clear
       install_frameworks
       ;;
       2) clear
       decompile_apks
       ;;
       3) clear
       add_translations
       ;;
       4) clear
       source_fix
       ;;
       5) clear
       mods
       ;;
       6) clear
       recompile_apks
       ;;
       7) clear
       inject_res
       ;;
       8) clear
       opt_png
       ;;
       9) clear
       zip_align
       ;;
       10) clear
       sign_menu
       ;;
       11) clear
       flashable
       ;;
       12) clear
       decompile_single
       ;;
       13) clear
       recompile_single
       ;;
       e) clear
       pull_apks
       ;;
       c) clear
       clean_menu
       ;;
       x) clear 
       exit;;
       *) echo ""
          echo "invalid menu choice"
       ;;
   esac
   echo ""
   echo "" 
   echo "[--- Press RETURN for menu ---]"
   read key
done

